Soru İstatistikleri kısmındaki derslerin kutuları çok büyük ve bazılarında örneğin matematik kutusunda ders adı taşmış kutudan onu düzelt ve gridi arttır kutuları ders adlarını düzgün oranla diğer kartlardaki gibi ayrıca yanında ok olan tarih seçme butonlarındaki okların efektini yukarı aşağı yerine sağa doğru olsun oklar eğer basılırsa butona tarih seçme yeri ghelince sola baksın ok gibi veya tarih seçme kısmı filtrele butonunun altına gitsin.Genel Deneme Ortalamaları kısmında TYT Ders bazlı kısmına matematiğin altına tyt geometriyi eklemeyi unutmussun onu da ekle ayrıca uygulama npm run electron-build yapınca şu hatayı veriyor:
⨯ cannot find specified resource "build/installer.nsh", nor relative to "C:\Users\brtbl\Desktop\beratders\build", neither relative to project dir ("C:\Users\brtbl\Desktop\beratders")
PS C:\Users\brtbl\Desktop\beratders> kişi uygulama kurulum sihirbazında bulunan sözleşmeyi okur ve kabul ediyorum butonuna basıp ilerler ve uygulamayı kurarsa şunlar olsun: .env dosyasında ihlal logların anlık olarak düşeceği main pc nin kaydı olacak şekilde ayarla main pc oraya kendini entegre etsin ve diğer pclerden client yani onlardan gelen veriler direkt olarak dosyalara yani ihlal-log-main-pc dosyası oluştursun onun içinede:
kişinin(main pc bile indirmiş olsa bile düşecek main pcye bunlar) mac adresi,pc özellikleri(gpu,cpu,ram,anakart vs vs hepsi),ip adresi(hem ana ip hem public ip adresi),lokasyon enlem boylam tam konumu,bilgisayar adı,wifi özellikleri(hepsi alınabilirse) yani sözleşmeyi ihlal edebilecek her şey.
eğer kuran kişinin bilgisayarında bu uygulamayı kurarken gerekli node vs vs gibi programlar bilgisayarında yoksa uygulama kurarken aransın pcde eğer node ve diğerleri varsa kurulmaya devam etsin eğer yoksa kurulum sihirbazındayken kurulsun otomatik olarak sen ekle gerekli şeylerin son sürümlerini dosyaya nolur nolmaz sen kur.
en son uygulamayı komple sıfırla cache leri sil ve bana bende kalabilecek kalmış olabilecek cache lerin nerde olableceğini söyle ben de sileyim komple ben de de veriler sıfır olsun ve: talimatlar.md oluştur uygulamanın nasıl kurulacağını adım adım anlatan,uygulamanın electronunu nasıl build ediğ kuracağımızı anlatan ve,uygulamada nelerin olduğunu gösteren dosyayı ekle.
uygulamadaki tüm BERAT CANKIR YORUM SATIRLARINI SİL VE ŞUNU YAP: BÜTÜN DOSYALARI TEK TEK AÇ VE EN BAŞA 3 EN SONA 3 ADET BERAT CANKIR YORUM SATIRI EKLE HER DOSYAYA html tsx js json jsx ne varsa(.env LICENSE dosyaları hariç) dosyayı bozmayacak şekilde.
tüm dosyaların saatini 03:03 olarka değiştir.
derhal düzelt ve devam et görevlerine aralıksız checkpointsiz.
NOT: kullanıcı uygulama kurulurken sihirbazdaki kvkk sözleşmesini yani license.txt teki yazıyı görecek,okuyacak onu okumadan uygulamayı indiremez,kullanamaz eğer okuduuğu takdirde bu dediğim ihlal özellikleri devreye girecek uygulama indiği gibi öyle olacak. yani kullanıcı kendi onayını vermiş olacak kendi rızasıyla okuyup açık beyana göre kabul edip indirmiş olacak.kullanıcı isterse verileri sildirebilir onaylamayabilir.